### ISSUE TITLE
Renaming the repo to something shorter?

### ISSUE THREAD

**Issue by elvismdev** [forumone/gesso-wp#34]
How do you guys feel about replacing this repo WordPress template long slug name "gesso-theme-wordpress" to something shorter a easy to remember for everyone in F1 and the outside community? If that's possible and since this is a port from original [Drupal's Gesso](https://github.com/forumone/gesso) theme, I'll propose to rename this to something like "gessowp" or "gesso-wp".

Github URL even looks like more marketable:
https://github.com/forumone/gessowp
https://github.com/forumone/gesso-wp

**Comment by coreylafferty** [comment]
Renamed to gesso-wp
