### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by elvismdev** [forumone/gesso-wp#37]
Ignore this specific files and directories from git tracking:

```
.DS_Store
node_modules
bower_components
.sass-cache
sass/partials/sass-globbing/
css/*.css
css/*.map
```

**Comment by coreylafferty** [comment]
Doesn't a file with those already exist?

**Comment by elvismdev** [comment]
Yes @coreylafferty, looking at it here on the repo I see there's one already https://github.com/forumone/gesso-wp/blob/master/.gitignore

Now wonder why it didn't came trough to a new project I just scaffolded using web-starter. Will double check later with @mortona42  if there's some reason for web-starter to ignore this file to be downloaded within the Gesso template of selected.
