### ISSUE TITLE
pattern-lab 404s

### ISSUE THREAD

**Issue by yumyo** [forumone/gesso-wp#38]
Hi,

I just started using Gesso after following the install instructions.

My pattern-lab public claims 14 missing resources, namely:

```
dropbutton.js?1487432497
collapse.js?1487432497
drupal.js?v=8.2.4
drupalSettingsLoader.js?v=8.2.4
jquery.once.min.js?v=2.1.1
jquery.min.js?v=2.1.4
dropbutton.js?1487432497
collapse.js?1487432497
drupal.js?v=8.2.4
drupalSettingsLoader.js?v=8.2.4
jquery.once.min.js?v=2.1.1
jquery.min.js?v=2.1.4
```

I've swapped the content of `/source/_meta/_00-head.twig` with `/source/_meta/_02-basic-head.twig` and the same for `_01-foot.twig` with `_03-basic-foot.twig` where I found those assets referenced. Then, I've regenerated pattern-lab multiple times but still, nothing changes. 

Even manually removing the `public` folder has no effect. What's the proper way to clean this pattern-lab install to work with WordPress, without any specific or project specific dependencies not required by Pattern-Lab?

**Comment by yumyo** [comment]
Don't mind, was a sync issue coming from my docker-unison image. A clean version for WP would be nice though )

**Comment by dmoon79** [comment]
@yumyo The version of Patternlab we suggest here is by no means necessary to run this theme. It just happens to be the one we use here at our agency. Theoretically, you can choose to install any version of Patternlab that is maintained by the Pattern lab team at > https://github.com/pattern-lab/  I don't think that they maintain a Wordpress specific version, but that definitely would be great!
