### ISSUE TITLE
Pattern-lab data [question]

### ISSUE THREAD

**Issue by yumyo** [forumone/gesso-wp#41]
Hi,
this is a "usage" / "best practice" question. 

I am wondering how to inject WP data in pattern-lab. I roughly see two approaches, one calling wp-load.php from pattern-lab, one using the WP REST API, then saving and accessing a JSON file from the _data or individual pattern folder. 

What is the optimal or easiest way in your experience? 
Do you have any implementation sample code?

**Comment by yumyo** [comment]
Well, guess the WP REST API is the best way not to touch Pattern-Lab and have the best of both worlds. 

powerful and easy to implement when combined with [Grunt Wget](https://github.com/shootaroo/grunt-wget) or [Grunt Curl](https://github.com/twolfson/grunt-curl) and optionally modifying the response to keep those files small and quick to read. 

Further advanced customizations could be achieved using [Grunt json-format](https://github.com/jahed/grunt-json-format) (eg. to remove array brackets []) and/or [Grunt json-bake](https://github.com/MathiasPaumgarten/grunt-json-bake) (to merge multiple files).

It remains interesting to understand if it's easy to add the [**Data Inheritance Plugin for Pattern Lab**](https://github.com/pattern-lab/plugin-php-data-inheritance) to inherit (thus share) data from patterns.

**Comment by coreylafferty** [comment]
As far as I know, we haven't tried to inject WP data into Pattern Lab.  In the 1.x version of the theme, Pattern Lab and WordPress were essentially separate (although they shared the same CSS and JS files).  The new 2.x release does tie them together, allowing WP to directly use Pattern Lab components. The theme now stores all the Pattern Lab content data in Yaml files, while WordPress templates now directly reference the Pattern Lab templates and pass them 'real' content from WP.
