### ISSUE TITLE
TimberHelper::get_comment_form() is now deprecated

### ISSUE THREAD

**Issue by elvismdev** [forumone/gesso-wp#45]
Has to be removed from [single.php](https://github.com/forumone/gesso-wp/blob/master/single.php)

https://timber.github.io/timber/#get_comment_form

**Comment by windycitymoon** [comment]
Opened a pull request in #46 to address this issue.

**Comment by elvismdev** [comment]
Closing this issue as it is now resolved on PR https://github.com/forumone/gesso-wp/pull/46
